import Foundation

enum ClipboardHistorySettings {
    enum Keys {
        static let enabled = "clipboardHistoryEnabled"
        static let retentionCount = "clipboardHistoryRetentionCount"
        static let retentionDays = "clipboardHistoryRetentionDays"
        static let excludedApps = "clipboardHistoryExcludedApps"
        static let saveDictations = "clipboardHistorySaveDictations"
        static let sounds = "clipboardHistorySounds"
        static let paused = "clipboardHistoryPaused"
    }

    static var isEnabled: Bool {
        get { UserDefaults.standard.object(forKey: Keys.enabled) as? Bool ?? true }
        set { UserDefaults.standard.set(newValue, forKey: Keys.enabled) }
    }
    static var retentionCount: Int {
        get { max(1, UserDefaults.standard.object(forKey: Keys.retentionCount) as? Int ?? 500) }
        set { UserDefaults.standard.set(max(1, newValue), forKey: Keys.retentionCount) }
    }
    static var retentionDays: Int {
        get { max(1, UserDefaults.standard.object(forKey: Keys.retentionDays) as? Int ?? 90) }
        set { UserDefaults.standard.set(max(1, newValue), forKey: Keys.retentionDays) }
    }
    static var excludedApps: Set<String> {
        get { Set(UserDefaults.standard.stringArray(forKey: Keys.excludedApps) ?? Self.defaultExcludedApps) }
        set { UserDefaults.standard.set(newValue.sorted(), forKey: Keys.excludedApps) }
    }
    static var saveDictations: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.saveDictations) }
        set { UserDefaults.standard.set(newValue, forKey: Keys.saveDictations) }
    }
    static var soundsEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.sounds) }
        set { UserDefaults.standard.set(newValue, forKey: Keys.sounds) }
    }
    static var isPaused: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.paused) }
        set { UserDefaults.standard.set(newValue, forKey: Keys.paused) }
    }

    static let defaultExcludedApps: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.Passwords",
        "com.apple.keychainaccess"
    ]
}

enum ClipboardExclusionPolicy {
    static let excludedPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    static func excludes(types: some Sequence<String>, sourceBundleIdentifier: String?, excludedApps: Set<String>) -> Bool {
        let typeSet = Set(types)
        return !typeSet.isDisjoint(with: excludedPasteboardTypes)
            || (sourceBundleIdentifier.map(excludedApps.contains) ?? false)
            || typeSet.contains(ClipboardManager.historyIgnoreType.rawValue)
            || typeSet.contains(ClipboardManager.pasteSessionType.rawValue)
    }
}
