import Foundation

enum ClipboardPanelPosition: String, CaseIterable, Identifiable {
    case lastLocation
    case centerScreen
    case pointer

    var id: String { rawValue }
}

enum ClipboardHistorySettings {
    enum Keys {
        static let enabled = "clipboardHistoryEnabled"
        static let windowPosition = "ClipboardHistoryWindowPosition"
        static let pasteOnClick = "clipboardHistoryPasteOnClick"
        static let doubleClickPaste = "clipboardHistoryDoubleClickPaste"
        static let showBadges = "clipboardHistoryShowBadges"
        static let updateAfterPaste = "clipboardHistoryUpdateAfterPaste"
        static let favoritesOnTop = "clipboardHistoryFavoritesOnTop"
        static let warnBeforeClear = "clipboardHistoryWarnBeforeClear"
        static let clearOnQuit = "clipboardHistoryClearOnQuit"
        static let clearOnRestart = "clipboardHistoryClearOnRestart"
        static let keepFavoritesOnClear = "clipboardHistoryKeepFavoritesOnClear"
        static let keepTaggedOnClear = "clipboardHistoryKeepTaggedOnClear"
        static let ignoreConfidential = "clipboardHistoryIgnoreConfidential"
        static let ignoreTransient = "clipboardHistoryIgnoreTransient"
        static let retentionCount = "clipboardHistoryRetentionCount"
        static let maximumItemSize = "clipboardHistoryMaximumItemSize"
        static let retentionByKind = "clipboardHistoryRetentionByKind"
        static let sort = "clipboardHistorySort"
        static let copyMergeEnabled = "clipboardHistoryCopyMergeEnabled"
        static let copyMergeSeparator = "clipboardHistoryCopyMergeSeparator"
        static let copyMergeUpdatesClipboard = "clipboardHistoryCopyMergeUpdatesClipboard"
        static let excludedApps = "clipboardHistoryExcludedApps"
        static let saveDictations = "clipboardHistorySaveDictations"
        static let sounds = "clipboardHistorySounds"
        static let paused = "clipboardHistoryPaused"
        static let copySound = "clipboardHistoryCopySound"
        static let pasteSound = "clipboardHistoryPasteSound"
        static let deleteSound = "clipboardHistoryDeleteSound"
        static let selectionSound = "clipboardHistorySelectionSound"
    }

    static var isEnabled: Bool {
        get { UserDefaults.standard.object(forKey: Keys.enabled) as? Bool ?? true }
        set { UserDefaults.standard.set(newValue, forKey: Keys.enabled) }
    }
    static var retentionCount: Int {
        get { max(1, UserDefaults.standard.object(forKey: Keys.retentionCount) as? Int ?? 500) }
        set { UserDefaults.standard.set(max(1, newValue), forKey: Keys.retentionCount) }
    }
    static var maximumItemSize: Int {
        get { max(1, UserDefaults.standard.object(forKey: Keys.maximumItemSize) as? Int ?? 50 * 1_024 * 1_024) }
        set { UserDefaults.standard.set(max(1, newValue), forKey: Keys.maximumItemSize) }
    }
    static var windowPosition: String {
        get { UserDefaults.standard.string(forKey: Keys.windowPosition) ?? "lastLocation" }
        set { UserDefaults.standard.set(newValue, forKey: Keys.windowPosition) }
    }
    static var panelPosition: ClipboardPanelPosition {
        get { ClipboardPanelPosition(rawValue: windowPosition) ?? .lastLocation }
        set { windowPosition = newValue.rawValue }
    }
    static func bool(_ key: String, defaultValue: Bool = false) -> Bool {
        UserDefaults.standard.object(forKey: key) as? Bool ?? defaultValue
    }
    static func set(_ value: Bool, for key: String) { UserDefaults.standard.set(value, forKey: key) }
    static var excludedApps: Set<String> {
        get { Set(UserDefaults.standard.stringArray(forKey: Keys.excludedApps) ?? Self.defaultExcludedApps) }
        set { UserDefaults.standard.set(newValue.sorted(), forKey: Keys.excludedApps) }
    }
    static var saveDictations: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.saveDictations) }
        set { UserDefaults.standard.set(newValue, forKey: Keys.saveDictations) }
    }
    static var soundsEnabled: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.sounds) }
        set { UserDefaults.standard.set(newValue, forKey: Keys.sounds) }
    }
    static var isPaused: Bool {
        get { UserDefaults.standard.bool(forKey: Keys.paused) }
        set { UserDefaults.standard.set(newValue, forKey: Keys.paused) }
    }

    static func soundEnabled(for key: String) -> Bool { bool(key) }

    static let defaultExcludedApps: [String] = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.bitwarden.desktop",
        "com.apple.Passwords",
        "com.apple.keychainaccess"
    ]
}

enum ClipboardExclusionPolicy {
    static let excludedPasteboardTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType"
    ]

    static func excludes(
        types: some Sequence<String>,
        sourceBundleIdentifier: String?,
        excludedApps: Set<String>,
        ignoreConfidential: Bool = true,
        ignoreTransient: Bool = true
    ) -> Bool {
        let typeSet = Set(types)
        let hasConfidential = typeSet.contains("org.nspasteboard.ConcealedType")
        let hasTransient = typeSet.contains("org.nspasteboard.TransientType")
            || typeSet.contains("org.nspasteboard.AutoGeneratedType")
        return (ignoreConfidential && hasConfidential)
            || (ignoreTransient && hasTransient)
            || (sourceBundleIdentifier.map(excludedApps.contains) ?? false)
            || typeSet.contains(ClipboardManager.historyIgnoreType.rawValue)
            || typeSet.contains(ClipboardManager.pasteSessionType.rawValue)
    }
}
