import SwiftUI
import AppKit

struct ClipboardManager {
    static let pasteSessionType = NSPasteboard.PasteboardType("com.arcusis.zerm.PasteSession")
    private static let sourceType = NSPasteboard.PasteboardType("org.nspasteboard.source")
    private static let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private static let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")

    enum ClipboardError: Error {
        case copyFailed
        case accessDenied
    }

    static func setClipboard(
        _ text: String,
        transient: Bool = false,
        sessionID: String? = nil,
        on pasteboard: NSPasteboard = .general
    ) -> Bool {
        // Prepare every representation before taking ownership of the live pasteboard. Calling
        // NSPasteboard.setString/setData repeatedly mutates the pasteboard change count for every
        // metadata type, which clipboard managers can surface as a burst of separate copies.
        // AppKit's NSPasteboardItem + writeObjects API publishes these representations together.
        let item = NSPasteboardItem()
        guard item.setString(text, forType: .string) else {
            return false
        }

        if let bundleIdentifier = Bundle.main.bundleIdentifier {
            guard item.setString(bundleIdentifier, forType: sourceType) else {
                return false
            }
        }

        if transient {
            guard item.setData(Data(), forType: transientType),
                  item.setData(Data(), forType: autoGeneratedType) else {
                return false
            }
        }

        if let sessionID {
            guard item.setString(sessionID, forType: pasteSessionType) else {
                return false
            }
        }

        pasteboard.clearContents()
        guard pasteboard.writeObjects([item]) else {
            return false
        }
        return pasteboard.string(forType: .string) == text
    }

    static func copyToClipboard(_ text: String) -> Bool {
        return setClipboard(text, transient: false)
    }

    static func getClipboardContent() -> String? {
        return NSPasteboard.general.string(forType: .string)
    }
}

struct ClipboardMessageModifier: ViewModifier {
    @Binding var message: String

    func body(content: Content) -> some View {
        content
            .overlay(
                Group {
                    if !message.isEmpty {
                        Text(message)
                            .font(.caption)
                            .foregroundColor(.green)
                            .padding(.horizontal, 8)
                            .padding(.vertical, 4)
                            .background(Color.green.opacity(0.1))
                            .cornerRadius(4)
                            .transition(.opacity)
                            .animation(.easeInOut, value: message)
                    }
                }
                .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .topTrailing)
                .padding()
            )
    }
}

extension View {
    func clipboardMessage(_ message: Binding<String>) -> some View {
        self.modifier(ClipboardMessageModifier(message: message))
    }
}
